spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Task_23
    username: user1
    password: user123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true